### ISSUE TITLE
JSP View 404 Not Found 에러 (Spring Boot 3.x + JSP)

### ISSUE THREAD

**Issue by Tae4an** [Tae4an/Smart-Office#39]
## 문제 상황
- Spring Boot 3.x + JSP 환경에서 View Resolver가 JSP 파일을 찾지 못하는 404 에러 발생
- 정확한 경로 설정과 의존성이 모두 있음에도 지속적으로 발생

## 환경
```gradle
plugins {
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'java'
    id 'war'
}

dependencies {
    implementation 'org.apache.tomcat.embed:tomcat-embed-jasper'
    implementation 'jakarta.servlet:jakarta.servlet-api'
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl'
}
```

### 1. ViewResolver 설정 확인 및 수정
```yaml
# application.yml
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
```

### 2. WebMvcConfigurer 구현 시도
```java
@Configuration
public class WebMvcConfig implements WebMvcConfigurer {
    @Override
    public void configureViewResolvers(ViewResolverRegistry registry) {
        InternalResourceViewResolver resolver = new InternalResourceViewResolver();
        resolver.setPrefix("/WEB-INF/views/");
        resolver.setSuffix(".jsp");
        resolver.setViewClass(JstlView.class);
        registry.viewResolver(resolver);
    }
}
```

### 3. 수동 ViewResolver Bean 등록
```java
@Configuration
public class ViewResolverConfig {
    @Bean
    public InternalResourceViewResolver viewResolver() {
        InternalResourceViewResolver resolver = new InternalResourceViewResolver();
        resolver.setPrefix("/WEB-INF/views/");
        resolver.setSuffix(".jsp");
        return resolver;
    }
}
```

### 4. 디버깅을 위한 로그 레벨 설정
```yaml
logging:
  level:
    org.springframework.web: TRACE
    org.springframework.web.servlet: TRACE
    org.springframework.web.servlet.view: TRACE
```

### 5. 로그 분석
```log
Forwarding to [/WEB-INF/views/login.jsp]
```
- 정확한 경로를 찾고 있으나 파일을 찾지 못하는 상황 확인

### 6. 프로젝트 구조 확인
```
src/
  main/
    webapp/
      WEB-INF/
        views/
          login.jsp
```
- 표준 WAR 구조를 따르고 있음을 확인

## 근본 원인
- IDE에서 main() 메소드로 직접 실행 시 webapp 디렉토리를 제대로 인식하지 못하는 문제
- Spring Boot의 실행 방식에 따른 클래스패스와 리소스 인식 차이

## 해결 방법
1. `gradle bootRun`으로 애플리케이션 실행
   - Spring Boot Gradle Plugin이 제공하는 정식 실행 방법 사용
   - webapp 디렉토리를 포함한 모든 리소스를 정확히 인식

## 교훈
1. Spring Boot + JSP 개발 시 실행 방식의 중요성
2. IDE의 기본 실행과 Gradle 실행의 차이 이해 필요
3. 개발 환경과 배포 환경의 일관성을 위해 `gradle bootRun` 또는 패키징된 war/jar 실행 권장

## 참고 사항
- Spring Boot 3.x 이상에서는 JSP 사용이 권장되지 않음
- 가능하다면 Thymeleaf 등 다른 템플릿 엔진 사용 고려
- 레거시 시스템 유지보수 시에만 JSP 사용 권장
