### ISSUE TITLE
Spring Boot + React 단일 패키징 설정 가이드

### ISSUE THREAD

**Issue by Tae4an** [Tae4an/Smart-Office#63]
## 📁 프로젝트 구조

```
project-root/
├── front/                  # React 프로젝트
│   ├── package.json
│   ├── src/
│   └── build/
└── service/               # Spring Boot 프로젝트
    ├── build.gradle
    ├── src/
    │   └── main/
    │       ├── java/
    │       └── resources/
    │           └── static/
    └── build/
        └── libs/
            └── project-name-0.0.1-SNAPSHOT.jar

```

## 🛠 개발 환경 설정

```yaml
JDK: 17 이상
Node.js: 22.11.0 이상
Spring Boot: 3.2.11
React: 18.x
Gradle: 8.x

```

### 권장 IDE 설정

- IntelliJ IDEA Ultimate (Spring Boot)
- VS Code (React)

### 1. WebConfig 설정

```java
@Configuration
public class WebConfig implements WebMvcConfigurer {
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/**")
               .addResourceLocations("classpath:/static/")
               .resourceChain(true);
    }

    @Controller
    public static class ReactController {
        @GetMapping(value = {"/", "/{x:[\\\\w\\\\-]+}", "/{x:^(?!api$).*$}/**/{y:[\\\\w\\\\-]+}"})
        public String getIndex() {
            return "/index.html";
        }
    }
}
```

### 2. application.yml 설정

```yaml
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: classpath:/static/
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      cache:
        period: 0

```

### 1. package.json 설정

```json
{
  "name": "front",
  "version": "0.1.0",
  "private": true,
  "homepage": ".", // 필수 설정
  // homepage를 "."으로 설정하는 이유:
  // 1. 상대 경로 사용: 모든 자산 경로가 index.html에 대해 상대적으로 설정됨
  // 2. 유연한 배포: 애플리케이션을 다른 경로나 서브디렉토리에 쉽게 배포 가능
  // 3. 경로 독립성: 빌드된 앱이 특정 URL에 종속되지 않음
  // 4. 정적 파일 서빙: Spring Boot의 정적 리소스 디렉토리에서 올바르게 서빙됨
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  }
}
```

### 2. Router 설정 (src/index.js)

```jsx
import { BrowserRouter } from 'react-router-dom';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <BrowserRouter>
    <App />
  </BrowserRouter>
);
```

### 1. build.gradle 설정

```groovy
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.11'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'com.github.node-gradle.node' version '2.2.4' // Node.js 및 npm 작업을 위한 Gradle 플러그인
}

// Node.js 설정
node {
    version = '22.11.0' // 사용할 Node.js 버전
    download = true // 필요시 Node.js 자동 다운로드
    workDir = file("${project.buildDir}/nodejs") // Node.js 작업 디렉토리
    npmWorkDir = file("${project.buildDir}/npm") // npm 작업 디렉토리
    nodeModulesDir = file("${project.projectDir}/../front") // node_modules 위치 (프론트엔드 디렉토리)
}

def frontDir = "$projectDir/../front" // 프론트엔드 프로젝트 디렉토리 정의

// React 의존성 설치 태스크
task installReactDeps(type: NpmTask) {
    workingDir = file(frontDir)
    args = ['install']
}

// React 빌드 태스크
task buildReact(type: NpmTask) {
    dependsOn installReactDeps // 의존성 설치 후 실행
    workingDir = file(frontDir)
    args = ['run', 'build']
}

// React 빌드 결과를 Spring Boot 정적 리소스 디렉토리로 복사
task copyReactBuild(type: Copy) {
    dependsOn buildReact // React 빌드 후 실행
    from("${frontDir}/build") {
        include "**/*" // 모든 파일 및 디렉토리 포함
    }
    into "${projectDir}/src/main/resources/static" // Spring Boot 정적 리소스 디렉토리
}

// Spring Boot JAR 빌드 시 React 빌드 및 복사 작업 포함
bootJar {
    dependsOn copyReactBuild // React 빌드 복사 후 JAR 생성
}
```

### 1. 개발 환경 실행

```bash
# React 개발 서버 실행 (front 디렉토리에서)
npm start

# Spring Boot 실행 (service 디렉토리에서)
./gradlew bootRun

```

### 2. 프로덕션 빌드

```bash
# 전체 빌드
./gradlew clean bootJar

# 실행
java -jar build/libs/[프로젝트명]-0.0.1-SNAPSHOT.jar
```

## 💡 Tips

1. **개발 생산성**
    - React 개발 시에는 npm start로 개발 서버 활용
    - API 테스트는 Postman이나 Swagger 활용
2. **디버깅**
    - React 개발자 도구 활용
    - Spring Boot 로그 레벨 설정
    
    ```yaml
    logging:
      level:
        org.springframework.web: DEBUG
    
    ```
    
3. **배포 전 체크리스트**
    - [ ]  React 빌드 경로 확인
    - [ ]  환경변수 설정 확인
    - [ ]  API 엔드포인트 설정 확인
    - [ ]  정적 리소스 캐싱 설정 확인

## 🏆 성공적인 설정의 결과

1. **단일 jar로 배포 가능**
2. **React SPA 라우팅 정상 작동**
3. **정적 리소스 최적화된 제공**
4. **API 통신 원활**

---

이 가이드를 따라 설정하면 Spring Boot와 React가 통합된 환경에서 효율적인 개발이 가능합니다! 🎉
